name: deploy
on:
  push:
    paths:
      - "snowflake_streamlit_apps/**"

jobs:
  version:
    name: "Deploy Streamlit Apps"
    runs-on: ubuntu-latest
    steps:
      # Checkout step is necessary if you want to use a config file from your repo
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # Snowflake CLI installation
      - uses: snowflakedb/snowflake-cli-action@v1.5

        # Use the CLI
      - name: Execute Snowflake CLI command
        run: |
          snow --version

      - name: Find Changed Apps
        id: detect
        run: |
          # List changed files
          git fetch origin ${{ github.base_ref }}
          changed=$(git diff --name-only ${{ github.sha }} ${{ github.event.before }} | grep '^snowflake_streamlit_apps/' | cut -d'/' -f2 | sort -u)

          if [ -z "$changed" ]; then
            echo "No apps changed. Exiting."
            exit 0
          fi

          echo "apps=$changed" >> $GITHUB_OUTPUT